import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import tseslint from "typescript-eslint";

// Every package runs `eslint` from its own folder; this file is found by walking up.
const WEB = "apps/web";

// eslint-config-next targets all files; scope its blocks (Next, React, a11y rules) to the web app.
const nextForWeb = nextVitals.map((config) => {
  const isGlobalIgnore = Object.keys(config).length === 1 && config.ignores;
  if (isGlobalIgnore) return config;
  const files = config.files ?? ["**/*.{js,jsx,mjs,ts,tsx,mts,cts}"];
  return { ...config, files: files.map((pattern) => `${WEB}/${pattern}`) };
});

export default defineConfig([
  globalIgnores([
    "**/.next/**",
    "**/out/**",
    "**/build/**",
    "**/next-env.d.ts",
    // Local data (uploads, sandbox workspaces with the agents' files and clones), never source.
    "**/.data/**",
    // Generated by the shadcn and AI Elements CLIs; kept as upstream ships them.
    `${WEB}/src/components/ui/**`,
    `${WEB}/src/components/ai-elements/**`,
    `${WEB}/src/hooks/use-mobile.ts`,
  ]),
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [tseslint.configs.recommended],
    // Same severities as eslint-config-next/typescript, which the web app used before.
    rules: {
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/no-unused-expressions": "warn",
    },
  },
  ...nextForWeb,
  {
    // The data access layer (server/query.ts): a query file exports reads wrapped in query() (which checks
    // the session), types and constants; nothing else, so no unchecked read can be exported by accident.
    files: [`${WEB}/src/server/queries/**/*.ts`],
    ignores: ["**/*.test.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "ExportNamedDeclaration > FunctionDeclaration",
          message: "Export reads as `export const name = query(async (...) => ...)` so they check the session.",
        },
        {
          selector:
            "ExportNamedDeclaration > VariableDeclaration > VariableDeclarator > :matches(ArrowFunctionExpression, FunctionExpression)",
          message: "Wrap exported reads in query() (or publicQuery() with a reason) so they check the session.",
        },
        {
          selector:
            "ExportNamedDeclaration > VariableDeclaration > VariableDeclarator > CallExpression[callee.name!=/^(query|publicQuery)$/]",
          message: "Wrap exported reads in query() (or publicQuery() with a reason), outermost.",
        },
        {
          selector: "ExportNamedDeclaration[exportKind='value'] > ExportSpecifier[exportKind='value']",
          message: "Export reads where they are declared, wrapped in query(); re-exports skip the check.",
        },
        {
          selector: ":matches(ExportDefaultDeclaration, ExportAllDeclaration[exportKind='value'])",
          message: "Query files export named, query()-wrapped reads only.",
        },
      ],
    },
  },
]);
