import {
  Activity,
  Anchor,
  Archive,
  Atom,
  Banknote,
  Bell,
  Blocks,
  BookOpen,
  Bot,
  BotMessageSquare,
  Braces,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  ChartColumn,
  ChartLine,
  ChartPie,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Cog,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dog,
  Dumbbell,
  Earth,
  Feather,
  FileText,
  Film,
  Flame,
  Folder,
  Gamepad2,
  Gavel,
  Ghost,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  Home,
  Image,
  Inbox,
  KanbanSquare,
  Key,
  Landmark,
  Languages,
  Leaf,
  Library,
  Lightbulb,
  ListChecks,
  Lock,
  type LucideIcon,
  Mail,
  Map as MapIcon,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  Mic,
  Microscope,
  Moon,
  Mountain,
  Music,
  Newspaper,
  NotebookPen,
  Package,
  Palette,
  PenLine,
  Phone,
  PiggyBank,
  Plane,
  Puzzle,
  Quote,
  Receipt,
  Rocket,
  Scale,
  ScanSearch,
  School,
  Search,
  Send,
  Server,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Sigma,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Sun,
  Table,
  Target,
  Telescope,
  Terminal,
  TrendingUp,
  Trophy,
  Truck,
  UserRound,
  Users,
  Utensils,
  Video,
  Wallet,
  Wand,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

/**
 * Icons an agent avatar can use, keyed by the kebab-case name stored in the database.
 * Order is the picker order; `tags` widen the search beyond the name.
 */
export const AGENT_ICONS: { name: string; Icon: LucideIcon; tags?: string }[] = [
  { name: "bot", Icon: Bot, tags: "robot ai assistant" },
  { name: "bot-message-square", Icon: BotMessageSquare, tags: "robot chat ai" },
  { name: "sparkles", Icon: Sparkles, tags: "magic ai star" },
  { name: "brain", Icon: Brain, tags: "mind think" },
  { name: "brain-circuit", Icon: BrainCircuit, tags: "ai mind" },
  { name: "cpu", Icon: Cpu, tags: "chip processor" },
  { name: "zap", Icon: Zap, tags: "fast lightning" },
  { name: "rocket", Icon: Rocket, tags: "launch growth" },
  { name: "wand", Icon: Wand, tags: "magic" },
  { name: "lightbulb", Icon: Lightbulb, tags: "idea" },
  { name: "target", Icon: Target, tags: "goal focus" },
  { name: "crown", Icon: Crown, tags: "leader boss" },
  { name: "star", Icon: Star },
  { name: "heart", Icon: Heart, tags: "love care" },
  { name: "flame", Icon: Flame, tags: "fire hot" },
  { name: "atom", Icon: Atom, tags: "science" },
  { name: "search", Icon: Search, tags: "find research" },
  { name: "scan-search", Icon: ScanSearch, tags: "find inspect" },
  { name: "telescope", Icon: Telescope, tags: "explore research" },
  { name: "microscope", Icon: Microscope, tags: "science lab research" },
  { name: "compass", Icon: Compass, tags: "navigate explore" },
  { name: "map", Icon: MapIcon, tags: "location travel" },
  { name: "globe", Icon: Globe, tags: "web world internet" },
  { name: "earth", Icon: Earth, tags: "world planet" },
  { name: "pen-line", Icon: PenLine, tags: "write edit" },
  { name: "feather", Icon: Feather, tags: "write" },
  { name: "notebook-pen", Icon: NotebookPen, tags: "write notes journal" },
  { name: "file-text", Icon: FileText, tags: "document" },
  { name: "book-open", Icon: BookOpen, tags: "read learn" },
  { name: "library", Icon: Library, tags: "books knowledge" },
  { name: "newspaper", Icon: Newspaper, tags: "news press" },
  { name: "quote", Icon: Quote, tags: "copy content" },
  { name: "languages", Icon: Languages, tags: "translate" },
  { name: "chart-column", Icon: ChartColumn, tags: "analytics data report" },
  { name: "chart-line", Icon: ChartLine, tags: "analytics trend" },
  { name: "chart-pie", Icon: ChartPie, tags: "analytics share" },
  { name: "trending-up", Icon: TrendingUp, tags: "growth sales" },
  { name: "calculator", Icon: Calculator, tags: "math finance" },
  { name: "sigma", Icon: Sigma, tags: "math sum" },
  { name: "database", Icon: Database, tags: "data storage" },
  { name: "table", Icon: Table, tags: "spreadsheet data" },
  { name: "code", Icon: Code, tags: "developer programming" },
  { name: "terminal", Icon: Terminal, tags: "shell developer" },
  { name: "braces", Icon: Braces, tags: "json code" },
  { name: "bug", Icon: Bug, tags: "debug qa test" },
  { name: "git-branch", Icon: GitBranch, tags: "git code" },
  { name: "server", Icon: Server, tags: "infra devops" },
  { name: "cloud", Icon: Cloud, tags: "infra devops" },
  { name: "workflow", Icon: Workflow, tags: "automation process" },
  { name: "blocks", Icon: Blocks, tags: "build modules" },
  { name: "puzzle", Icon: Puzzle, tags: "integration plugin" },
  { name: "wrench", Icon: Wrench, tags: "tools fix" },
  { name: "hammer", Icon: Hammer, tags: "build tools" },
  { name: "cog", Icon: Cog, tags: "settings operations" },
  { name: "settings-2", Icon: Settings2, tags: "settings config" },
  { name: "shield", Icon: Shield, tags: "security" },
  { name: "shield-check", Icon: ShieldCheck, tags: "security compliance" },
  { name: "lock", Icon: Lock, tags: "security privacy" },
  { name: "key", Icon: Key, tags: "access secret" },
  { name: "scale", Icon: Scale, tags: "legal law justice" },
  { name: "gavel", Icon: Gavel, tags: "legal law court" },
  { name: "landmark", Icon: Landmark, tags: "bank government" },
  { name: "briefcase", Icon: Briefcase, tags: "business work" },
  { name: "building-2", Icon: Building2, tags: "company office" },
  { name: "store", Icon: Store, tags: "shop ecommerce" },
  { name: "shopping-cart", Icon: ShoppingCart, tags: "shop ecommerce sales" },
  { name: "package", Icon: Package, tags: "product delivery" },
  { name: "truck", Icon: Truck, tags: "delivery logistics" },
  { name: "wallet", Icon: Wallet, tags: "money finance" },
  { name: "banknote", Icon: Banknote, tags: "money finance cash" },
  { name: "receipt", Icon: Receipt, tags: "invoice accounting" },
  { name: "credit-card", Icon: CreditCard, tags: "payment" },
  { name: "piggy-bank", Icon: PiggyBank, tags: "savings budget" },
  { name: "mail", Icon: Mail, tags: "email" },
  { name: "message-square", Icon: MessageSquare, tags: "chat support" },
  { name: "messages-square", Icon: MessagesSquare, tags: "chat conversation" },
  { name: "megaphone", Icon: Megaphone, tags: "marketing announce" },
  { name: "send", Icon: Send, tags: "outreach message" },
  { name: "phone", Icon: Phone, tags: "call support" },
  { name: "bell", Icon: Bell, tags: "alert notify" },
  { name: "users", Icon: Users, tags: "team people hr" },
  { name: "user-round", Icon: UserRound, tags: "person profile" },
  { name: "handshake", Icon: Handshake, tags: "deal partner sales" },
  { name: "heart-handshake", Icon: HeartHandshake, tags: "support care" },
  { name: "graduation-cap", Icon: GraduationCap, tags: "education teach learn" },
  { name: "school", Icon: School, tags: "education" },
  { name: "stethoscope", Icon: Stethoscope, tags: "health medical" },
  { name: "activity", Icon: Activity, tags: "health monitor" },
  { name: "calendar", Icon: Calendar, tags: "schedule planning" },
  { name: "clock", Icon: Clock, tags: "time schedule" },
  { name: "list-checks", Icon: ListChecks, tags: "todo tasks" },
  { name: "clipboard-list", Icon: ClipboardList, tags: "tasks checklist" },
  { name: "kanban-square", Icon: KanbanSquare, tags: "board project" },
  { name: "inbox", Icon: Inbox, tags: "email triage" },
  { name: "folder", Icon: Folder, tags: "files" },
  { name: "archive", Icon: Archive, tags: "storage" },
  { name: "image", Icon: Image, tags: "picture design" },
  { name: "camera", Icon: Camera, tags: "photo" },
  { name: "palette", Icon: Palette, tags: "design art color" },
  { name: "video", Icon: Video, tags: "media" },
  { name: "film", Icon: Film, tags: "media movie" },
  { name: "music", Icon: Music, tags: "audio" },
  { name: "mic", Icon: Mic, tags: "audio podcast voice" },
  { name: "headphones", Icon: Headphones, tags: "audio support" },
  { name: "plane", Icon: Plane, tags: "travel" },
  { name: "car", Icon: Car, tags: "travel auto" },
  { name: "home", Icon: Home, tags: "house real estate" },
  { name: "utensils", Icon: Utensils, tags: "food restaurant" },
  { name: "coffee", Icon: Coffee, tags: "cafe break" },
  { name: "dumbbell", Icon: Dumbbell, tags: "fitness sport" },
  { name: "trophy", Icon: Trophy, tags: "win award" },
  { name: "gamepad-2", Icon: Gamepad2, tags: "games" },
  { name: "leaf", Icon: Leaf, tags: "nature eco" },
  { name: "mountain", Icon: Mountain, tags: "nature outdoor" },
  { name: "sun", Icon: Sun, tags: "day weather" },
  { name: "moon", Icon: Moon, tags: "night" },
  { name: "anchor", Icon: Anchor, tags: "stable" },
  { name: "dog", Icon: Dog, tags: "pet animal" },
  { name: "cat", Icon: Cat, tags: "pet animal" },
  { name: "ghost", Icon: Ghost, tags: "fun" },
  { name: "smile", Icon: Smile, tags: "happy fun" },
];

const BY_NAME = new Map(AGENT_ICONS.map((i) => [i.name, i.Icon]));

/** The icon for a stored name; unknown names fall back to the robot. */
export const agentIcon = (name: string): LucideIcon => BY_NAME.get(name) ?? Bot;

/**
 * Preset color pairs: a soft background with a matching strong foreground.
 * The picker offers these first; any hex color can still be set by hand.
 */
export const AVATAR_PALETTE: { color: string; background: string }[] = [
  { color: "#6d28d9", background: "#ede9fe" }, // violet
  { color: "#4338ca", background: "#e0e7ff" }, // indigo
  { color: "#1d4ed8", background: "#dbeafe" }, // blue
  { color: "#0369a1", background: "#e0f2fe" }, // sky
  { color: "#0f766e", background: "#ccfbf1" }, // teal
  { color: "#047857", background: "#d1fae5" }, // emerald
  { color: "#4d7c0f", background: "#ecfccb" }, // lime
  { color: "#a16207", background: "#fef9c3" }, // yellow
  { color: "#c2410c", background: "#ffedd5" }, // orange
  { color: "#be123c", background: "#ffe4e6" }, // rose
  { color: "#be185d", background: "#fce7f3" }, // pink
  { color: "#a21caf", background: "#fae8ff" }, // fuchsia
  { color: "#334155", background: "#e2e8f0" }, // slate
  { color: "#ffffff", background: "#18181b" }, // ink
  { color: "#ffffff", background: "#6d28d9" }, // solid violet
  { color: "#ffffff", background: "#059669" }, // solid green
];
