import { customType, timestamp, uuid } from "drizzle-orm/pg-core";

export const EMBEDDING_DIMENSIONS = 768;

export const id = () => uuid().primaryKey().defaultRandom();

export const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();

export const updatedAt = () =>
  timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date());

/**
 * A full-text search vector. drizzle-orm has no tsvector column, so it is a custom type; the columns are
 * generated by Postgres from the text they index and never written by the app.
 */
export const tsvector = customType<{ data: string }>({ dataType: () => "tsvector" });
